django_dependent_dropdown/django_dependent_dropdown/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('persons.urls')),
]

django_dependent_dropdown/persons/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    # path('', views.PersonListView.as_view(), name='person_changelist'),
    # path('add/', views.PersonCreateView.as_view(), name='person_add'),
    # path('<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    # path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('', views.PersonListView.as_view(), name='person_changelist'),
    path('add/', views.PersonCreateView, name='person_add'),
    path('<int:pk>/', views.PersonUpdateView, name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

]

django_dependent_dropdown/persons/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField('Birth Day',null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ManyToManyField(City,null=True)

    def __str__(self):
        return self.name

django_dependent_dropdown/persons/forms.py
from django import forms
from .models import Person, City


class PersonForm(forms.ModelForm):


    class Meta:
        model = Person
        fields = ('name', 'birthdate', 'country', 'city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()
        self.fields["city"].widget = forms.widgets.CheckboxSelectMultiple()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
                # self.fields["city"].widget = forms.widgets.CheckboxSelectMultiple()
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')
            # self.fields["city"].widget = forms.widgets.CheckboxSelectMultiple()

django_dependent_dropdown/persons/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from .models import Person, City
from .forms import PersonForm


class PersonListView(ListView):
    model = Person
    context_object_name = 'people'

#
# class PersonCreateView(CreateView):
#     model = Person
#     form_class = PersonForm
#     success_url = reverse_lazy('person_changelist')
#
#
# class PersonUpdateView(UpdateView):
#     model = Person
#     form_class = PersonForm
#     success_url = reverse_lazy('person_changelist')
#
#
# def load_cities(request):
#     country_id = request.GET.get('country')
#     cities = City.objects.filter(country_id=country_id).order_by('name')
#     return render(request, 'persons/city_dropdown_list_options.html', {'cities': cities})



#this is function base django dependent dropdown
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PersonForm
from .models import Person, City


def PersonCreateView(request):
    form = PersonForm()
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'persons/home.html', {'form': form})


def PersonUpdateView(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonForm(instance=person)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'persons/home.html', {'form': form})


# AJAX
def load_cities(request):
    country_id = request.GET.get('country_id')
    cities = City.objects.filter(country_id=country_id).all()
    return render(request, 'persons/city_dropdown_list_options.html', {'cities': cities})

django_dependent_dropdown/persons/templates/persons/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple ERP{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  </head>
  <body>
    <h1>Simple ERP</h1>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>

django_dependent_dropdown/persons/templates/persons/city_dropdown_list_options.html
{% load static %}
<style>
        #id_city {
            width: 100%;
        }
    </style>
<!--<option value="">---------</option>-->
{% for city in cities %}
<!--<input type="checkbox" value="{{ city.pk }}" name="{{ city.name }}">-->

        <input type="checkbox" value="{{city.id}}" name="city">{{ city.name }}<br>

<!--<option value="{{ city.pk }}">{{ city.name }}</option>-->
{% endfor %}

django_dependent_dropdown/persons/templates/persons/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
<h2>Person Form</h2>

<form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>

django_dependent_dropdown/persons/templates/persons/person_form.html
{% extends 'persons/base.html' %}

{% block content %}

  <h2>Person Form</h2>

  <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#personForm").attr("data-cities-url");
      var countryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_city").html(data);
        }
      });

    });
  </script>

{% endblock %}

django_dependent_dropdown/persons/templates/persons/person_list.html
{% extends 'persons/base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}
  <h2>Human Resources Module » People Management</h2>

  <p>
    <a href="{% url 'person_add' %}">Add person</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Country</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      {% for person in people %}
        <tr>
          <td><a href="{% url 'person_change' person.pk %}">{{ person.name }}</a></td>
          <td>{{ person.birthdate }}</td>
          <td>{{ person.country.name }}</td>
          <td>
            {% for course in person.city.all %}
                   {{ course.name }}
            {% endfor%}

          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'person_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}